# Generated by Django 3.2.18 on 2023-05-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_remove_travelplan_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='caption',
            field=models.CharField(default='', max_length=30),
        ),
    ]
