# Generated by Django 3.2.18 on 2023-05-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_travelplan_image_filter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelplan',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='travelplan',
            name='image2',
            field=models.ImageField(blank=True, default='../https://res.cloudinary.com/dqgs0kltd/image/upload/v1673026764/samples/ecommerce/accessories-bag.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='image3',
            field=models.ImageField(blank=True, default='../https://res.cloudinary.com/dqgs0kltd/image/upload/v1673026764/samples/ecommerce/accessories-bag.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='image4',
            field=models.ImageField(blank=True, default='../https://res.cloudinary.com/dqgs0kltd/image/upload/v1673026764/samples/ecommerce/accessories-bag.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='image5',
            field=models.ImageField(blank=True, default='../https://res.cloudinary.com/dqgs0kltd/image/upload/v1673026764/samples/ecommerce/accessories-bag.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='image6',
            field=models.ImageField(blank=True, default='../https://res.cloudinary.com/dqgs0kltd/image/upload/v1673026764/samples/ecommerce/accessories-bag.jpg', upload_to='images/'),
        ),
    ]
