# Generated by Django 3.2.18 on 2023-05-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20230503_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='image_filter',
            field=models.CharField(default='normal', max_length=40),
        ),
    ]
