# Generated by Django 3.2.18 on 2023-05-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_travelplan_image_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='image_filter',
            field=models.CharField(default='normal', max_length=50),
        ),
    ]
