# Generated by Django 3.2.18 on 2023-05-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_travelplan_image_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='caption',
            field=models.CharField(default='', max_length=30),
        ),
    ]
