# Generated by Django 3.2.18 on 2023-05-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_travelplan_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
