# Generated by Django 3.2.18 on 2023-05-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20230506_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
