# Generated by Django 3.2.18 on 2023-05-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_image',
            field=models.ImageField(blank=True, default='../sample.jpg ', upload_to='images/'),
        ),
    ]
